name: .NET Core CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/your-project.sln

      - name: Build project
        run: dotnet build src/your-project.sln --configuration Release

      - name: Run tests
        run: dotnet test src/your-project.sln
